### ISSUE TITLE
sorryconz.com

### ISSUE THREAD

**Issue by Sorryconz** [Sorryconz/sorryconz.io#1]

**Comment by sudeepkanda** [comment]
i am new to opensource , i didn't understand the issue could you elaborate so that I can help you

**Comment by bayron-nieto** [comment]
Hello, my name is Bayron grandson, I'm new to programming, I'm learning on my own and I just wanted to try something, hehe 😂Example:

> download Google chat
-  create a space 
- agregar githubchat de Google, 
- then I created a chat space I included Google's githubchat to the chst space 
I'm just testing how things work (trial and error)but I have a project in mind but I need to get informed, 
learn to program and standards 
If you have any advice for me I would greatly appreciate it, I have struggled a lot since it is a lot of lonquebyay quensprender and I still don't understand many basic concepts 
este es mi correo personal, 
bayron.omar.nieto@gmail.com

@sudeepkanda Thank you very much for your interest. If you are interested in my project, you tell me what I have to do, I will explain it to you and with some duet effort we will start it running.

**Comment by bayron-nieto** [comment]
Hello, my name is Bayron grandson, I'm new to programming, I'm learning on my own and I just wanted to try something, hehe 😂Example:

> download Google chat
-  create a space 
- agregar githubchat de Google, 
- then I created a chat space I included Google's githubchat to the chst space 
I'm just testing how things work (trial and error)but I have a project in mind but I need to get informed, 
learn to program and standards 
If you have any advice for me I would greatly appreciate it, I have struggled a lot since it is a lot of lonquebyay quensprender and I still don't understand many basic concepts 
este es mi correo personal, 
bayron.omar.nieto@gmail.com

@sudeepkanda Thank you very much for your interest. If you are interested in my project, you tell me what I have to do, I will explain it to you and with some duet effort we will start it running.

**Comment by sudeepkanda** [comment]
wow ! bayron grandson, I wish you good luck in this programming journey.
let us collaborate and do projects in the future If have any requirements I will reach you out.
if you need any help reach me out @ sudeepkanda@gmail.com

**Comment by Sorryconz** [comment]
> _No se proporciona descripción._
